# Configuration file for AiderAgent

# Path to the prompt markdown file
prompt: "default_prompt.md"

# Model configurations
coder_model: "deepseek-coder-33b-instruct"
evaluator_model: "deepseek-coder-33b-instruct"

# Execution settings
max_iterations: 3
execution_command: "python src/main.py"

# File access controls
context_editable:
  - "src/main.py"
  - "src/utils.py"
context_read_only:
  - "README.md"
  - "requirements.txt"

# Evaluation settings
evaluator: "default"
